---

- name: Create directory
  become: yes
  file:
    path: "/home/{{ ansible_user }}/setup"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy setup file to remote
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/setup/docker-compose.yml"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
