---

web_dir: /home/{{ ansible_user }}/web_setup
couchdb_dir: /home/{{ ansible_user }}/couchdb_setup
couchdb_data_dir: /home/{{ ansible_user }}/couchdb_setup/data
crawler_dir: /home/{{ ansible_user }}/crawler_setup

# number of webservices to distribute among all nodes
num_scale_webservices: 4

couchdb_username: Admin
couchdb_password: admin
couchdb_cookie: couchcookie
couchdb_secret: couchsecret

crawler_database: tweets_v1
crawler_tag: "{{ couchdb_hostname }}_crawler"

coordination_node_ip: 45.113.233.94
