---

- name: Check the status of cluster CouchDB membership
  when: inventory_hostname in groups['master']
  become: yes
  command: "curl http://{{ couchdb_username }}:{{ couchdb_password }}@0.0.0.0:5984/_membership"
  register: output
  ignore_errors: yes

- debug: var=output.stdout

- name: Copy Crawler Dockerfile to remote
  become: yes
  template:
    src: Dockerfile.j2
    dest: "{{ crawler_dir }}/Dockerfile"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy Crawler python file to remote
  become: yes
  template:
    src: crawler.py.j2
    dest: "{{ crawler_dir }}/crawler.py"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Start Crawler service (Crawl place -- "{{ crawl_place }}")
  become: yes
  command: "docker build -t {{ crawler_tag }} ."
  args:
    chdir: "{{ crawler_dir }}"

- name: Start Crawler service (Crawl place -- "{{ crawl_place }}")
  become: yes
  command: "docker run -d {{ crawler_tag }}"
  args:
    chdir: "{{ crawler_dir }}"
