---

- name: Leave previous swarm on a node
  become: yes
  command: docker swarm leave --force
  ignore_errors: yes

- name: Reload vars
  include_vars: host_vars/join_token.yml

- name: Join a swarm
  become: yes
  command: "{{join_token}}"
