---

- hosts: master
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - common

- hosts: slave1
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - common

- hosts: master
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - setup_swarm_master

- hosts: slave1
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - setup_swarm_slave

- hosts: master
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - deploy_couchdb_master

- hosts: slave1
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - deploy_couchdb_slave

- hosts: master
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    - deploy_crawler
