---

- hosts: master
  vars_files:
    - host_vars/vars.yml
  become: yes
  roles:
    # - common
    - master_setup

- hosts: slave1
  become: yes
  roles:
    # - common
    - slave_setup

- hosts: master
  become: yes
  roles:
    - master_deploy
