---

- name: Leave previous swarm on a node
  become: yes
  command: docker swarm leave --force
  args:
    chdir: "/home/{{ ansible_user }}/setup"
  ignore_errors: yes

- name: Reload vars
  include_vars: host_vars/vars.yml

- name: Join a swarm
  become: yes
  command: "{{join_token}}"
