---

- name: Copy CouchDB setup file to remote
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: "{{ couchdb_dir }}/docker-compose.yml"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Start CouchDB service -- "{{couchdb_hostname}}"
  become: yes
  command: "docker stack deploy -c docker-compose.yml {{ couchdb_hostname }}"
  args:
    chdir: "{{ couchdb_dir }}"

# - name: Check the status of cluster CouchDB membership
#   become: yes
#   uri:
#     url: "{{ ansible_default_ipv4.address }}:5984/_membership"
#     method: GET
#     user: "{{ couchdb_username }}"
#     password: "{{ couchdb_password }}"
#   register: output

- name: Check the status of cluster CouchDB membership
  become: yes
  command: "curl -X GET 0.0.0.0:5984/_membership -u {{ couchdb_username }}:{{ couchdb_password }}"
  register: output
  ignore_errors: yes

- debug: var=output.stdout
  ignore_errors: yes
