---

- name: Copy html to remote
  become: yes
  synchronize:
    src: ./web_html
    dest: "{{ home_dir }}"

- name: Copy Web service setup file to remote
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: "{{ home_dir }}/web_html/{{ item }}"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - docker-compose.yml
    - Dockerfile
    - local.conf

- name: Build Webservice -- "{{couchdb_hostname}}"
  become: yes
  command: "docker-compose up -d"
  args:
    chdir: "{{ home_dir }}/web_html"

# - name: Start Web service
#   become: yes
#   command: docker stack deploy -c docker-compose.yml webservice
#   args:
#     chdir: "{{ home_dir }}/web_html/"
#
# - name: Scale Web service to all nodes
#   become: yes
#   command: "docker service scale webservice_web={{ num_scale_webservices }}"
#
# - name: Check the status of Web service
#   become: yes
#   command: docker service ps webservice_web
#   register: output
#
# - debug: var=output.stdout
