---

- name: Create directory
  become: yes
  file:
    path: "/home/{{ ansible_user }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - setup

- name: Copy setup file to remote
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/setup/docker-compose.yml"
    mode: 0744
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy html to remote
  become: yes
  synchronize:
    src: ./web_html
    dest: "/home/{{ ansible_user }}/setup"

- name: Leave previous swarm on a node
  become: yes
  command: docker swarm leave --force
  args:
    chdir: "/home/{{ ansible_user }}/setup"
  ignore_errors: yes

- name: Setup master node
  become: yes
  shell: docker swarm init

- name: Get the join-token of worker
  become: yes
  shell: docker swarm join-token worker | grep "docker swarm join"
  register: output

- name: Modify join_token
  become: yes
  local_action:
    module: lineinfile
    dest: ./host_vars/vars.yml
    regexp: 'join_token:'
    line: 'join_token: {{ output.stdout }}'


# - debug: join_token=output

# - debug: var=join_token.stdout

# - debug: var=hostvars['join_token']

# - name: Start Doker-Compose Setup
#   become: yes
#   command: docker-compose up -d
#   args:
#     chdir: "/home/{{ ansible_user }}/setup"
#
# - name: Check Apache Service
#   become: yes
#   command: docker ps
#   args:
#     chdir: "/home/{{ ansible_user }}/setup"
#   register: web_url
#
# # show the url of web server
# - debug: var=web_url.stdout_lines
